---
- name: Restart node_exporter
  listen: "restart node_exporter"
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: "{{ node_exporter_service }}"
    state: restarted

- name: Reload node_exporter
  listen: "reload node_exporter"
  become: true
  ansible.builtin.systemd:
    name: "{{ node_exporter_service }}"
    state: reloaded
