- name: Setup monitoring stack
  hosts: monitoring
  become: true
  gather_facts: true

  tasks:
    - name: Setup prometheus role
      ansible.builtin.import_role:
        name: prometheus
      tags: prometheus
      when: inventory_hostname in groups['prometheus']

    - name: Setup node_exporter role
      ansible.builtin.import_role:
        name: node_exporter
      tags: node_exporter
      when: inventory_hostname in groups['node_exporter']

    - name: Reconfigure prometheus_target
      ansible.builtin.import_role:
        name: prometheus
        tasks_from: static_targets.yml
      tags:
        - node_exporter
        - prometheus
      when: inventory_hostname in groups['node_exporter']
      delegate_to: prometheus

    - name: Setup elk role
      environment:
        http_proxy: "http://192.168.200.10:20171"
        https_proxy: "http://192.168.200.10:20171"
      ansible.builtin.import_role:
        name: elk
      when: inventory_hostname in groups['elk']
      tags: elk

    - name: Setup fluentbit role
      ansible.builtin.import_role:
        name: fluentbit
      when: inventory_hostname in groups['fluentbit']
      tags: fluentbit
