---
node_exporter_group: "node-exp"
node_exporter_user: "node-exp"
node_exporter_service: "node_exporter"


node_exporter_version: 1.7.0
node_exporter_binary_local_dir: ""
node_exporter_binary_url: "https://github.com/{{ _node_exporter_repo }}/releases/download/v{{ node_exporter_version }}/\
                           node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"

node_exporter_web_listen_address: "0.0.0.0:9100"
node_exporter_web_telemetry_path: "/metrics"

node_exporter_textfile_dir: "/var/lib/node_exporter"
node_exporter_config_dir: "/etc/node_exporter"

node_exporter_tls_server_config: {}

node_exporter_http_server_config: {}

node_exporter_enabled_collectors:
  - systemd
  - textfile:
      directory: "{{ node_exporter_textfile_dir }}"
#  - filesystem:
#      ignored-mount-points: "^/(sys|proc|dev)($|/)"
#      ignored-fs-types: "^(sys|proc|auto)fs$"

node_exporter_disabled_collectors: []

node_exporter_binary_install_dir: "/usr/local/bin"

node_exporter_update_prometheus: false
node_exporter_prometheus_host: "prometheus"
node_exporter_promethues_config_dir: "/etc/prometheus/"
node_exporter_prometheus_labels:

