---
- name: Add required dependencies.
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - gpg
    state: present

- name: Add Elasticsearch apt key
  ansible.builtin.apt_key:
    url: "{{ _elk_es_gpg_key }}"
    state: present

- name: Add Elasticsearch repository.
  ansible.builtin.apt_repository:
    repo: "deb {{ elk_es_deb_repo }} stable main"
    state: present
    update_cache: true
