---
- name: Setup prometheus group
  ansible.builtin.group:
    name: "{{ prometheus_group }}"
    system: true
    state: present

- name: Setup prometheus user
  ansible.builtin.user:
    name: "{{ prometheus_user }}"
    comment: "Prometheus user"
    group: "{{ prometheus_group }}"
    create_home: false
    system: true
    home: "{{ prometheus_db_dir }}"
    shell: "/bin/false"
    state: present

- name: Setup prometheus config folder
  ansible.builtin.file:
     path: "{{ item }}"
     group: "{{ prometheus_group }}"
     mode: "0750"
     owner: root
     state: "directory"
  with_items:
    - "{{ prometheus_config_dir }}"
    - "{{ prometheus_config_dir }}/rules"
    - "{{ prometheus_config_dir }}/file_sd"

- name: Setup prometheus database folder
  ansible.builtin.file:
     path: "{{ prometheus_db_dir }}"
     group: "{{ prometheus_group }}"
     mode: "0755"
     owner: "{{ prometheus_user }}"
     state: "directory"

- name: Download prometheus binary
  ansible.builtin.get_url:
    url: "{{ prometheus_binary_url }}"
    dest: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
    mode: 0644
  register: _download_archive
  until: _download_archive is succeeded
  retries: 5
  delay: 2
  delegate_to: localhost
  check_mode: false
  become: false

- name: Unpack prometheus binaries
  ansible.builtin.unarchive:
    src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
    dest: "/tmp"
    creates: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/prometheus"
  delegate_to: localhost
  check_mode: false
  become: false

- name: Copy prometheus and promtool binaries to the host
  ansible.builtin.copy:
    src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}"
    dest: "{{ prometheus_binary_install_dir }}/{{ item }}"
    mode: 0755
    owner: root
    group: root
    remote_src: false
  with_items:
    - prometheus
    - promtool
  notify:
    - restart prometheus

- name: Copy official console templates
  ansible.builtin.copy:
    src: "/tmp/prometheus-{{ prometheus_version }}.linux-amd64/{{ item }}/"
    dest: "{{ prometheus_config_dir }}/{{ item }}/"
    mode: 0644
    owner: root
    group: root
    remote_src: false
  with_items:
    - console_libraries
    - consoles
  notify:
    - restart prometheus

- name: Create systemd service unit
  ansible.builtin.template:
    src: prometheus.service.j2
    dest: "/etc/systemd/system/{{prometheus_service}}.service"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart prometheus
