---
- name: Install prometheus
  ansible.builtin.import_tasks:
    file: install.yml

- name: Configure prometheus
  ansible.builtin.import_tasks:
    file: "configure.yml"

- name: Configure static targets
  ansible.builtin.import_tasks:
    file: "static_targets.yml"

- name: Ensure prometheus service is started and enabled
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: "{{ prometheus_service }}"
    state: started
    enabled: true
